
changelog:
  sections:
  - title: "Enhancements"
    labels: ["new"]
  - title: "Bugs"
    labels: ["fix"]
  - title: "Dependency Upgrades"
    labels: ["dependency"]
  - title: "documentation"
    labels: ["documentation"]
 
