name: ci build
on: 
  push:
    branches: [main]
  pull_requests:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir-p venky/

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: touch /venky/text.txt
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: touch /venky/text.t
