name: ci build
on: 
  push:
    branches: [main]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: create folder
        run: mkdir  venky/

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: create folder
        run: mkdir  venky1/
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: create folder
        run: mkdir  venky2/
