name: ci build
on: 
  push:
    branches: [main]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: create folder
        run: mkdir -p venky/

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: create folder
        run: touch /venky/text.txt
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: create folder
        run: touch /venky/text.txt
