# .github/workflows/issue-on-push.yml
on: [push]
name: Create an issue on push
permissions:
  contents: read
  issues: write 
jobs:
  comment:
    runs-on: ubuntu-latest
    steps: 
    - name: create th issue using REST API
      run: |
       curl -X POST \
       https://github.com/sendevenkatesh/quest-global/${{ github.quest-global }}/issues\
       
       -H "Content-Type: application/json"\
       
       --data '{
         "title": "issue:" ${{ github.sha }}",
         "body": "this issue Action workflow **${{ github.workflow}}**. \n\n
         }' \
       --fail
       
       
      
   
       
  comment1:
     runs-on: ubuntu-latest
     needs: comment
     env: 
      WEBHOOK: ${{ secrets.WEBHOOK }}
     steps: 
      - run: |
          curl -d '{"type":"messege", "text":"New issue created"}'\
          -X POST -H "Content-Type: application/json"\
          https://webhook.site/4f0f269d-5f1b-4261-a0de-c3f815dad0e5\
         
         #curl \
         #-X GET \
         #-H "Accept: application/json" \
         #https://referenceapplicationwithswagger1-relaxed-bushbuck-vz.cloud.pcftest.com/hello/vamshi
         
       
         
