name: webhook
on: 
  push
 
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
     - name: create
       run: mkdir folder
       
  comment1:
     runs-on: ubuntu-latest
     needs: comment
     env: 
      WEBHOOK: ${{ secrets.WEBHOOK }}
     steps: 
      - run: |
         curl \
         -X GET \
         -H "Accept: application/vnd.github.v3+json" \
         https://referenceapplicationwithswagger1-relaxed-bushbuck-vz.cloud.pcftest.com/hello/vamshi
         
       
        # curl \
         #-X GET \
         #-H "Accept: application/vnd.github.v3+json" \
         #https://webhook.site/4f0f269d-5f1b-4261-a0de-c3f815dad0e5\
         
        # curl \
         #-X POST \
         #-H "Accept: application/vnd.github.v3+json" \
          #https://webhook.site/4f0f269d-5f1b-4261-a0de-c3f815dad0e5\
      
          #curl \
          #-H "Accept: application/vnd.github.v3+json" \ 
          #https://github.com/sendevenkatesh/quest-global/settings/hooks\
         
