# .github/workflows/issue-on-push.yml
on: [push]
name: Create an issue on push
permissions:
  contents: read
  issues: write 
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
  comment1:
     runs-on: ubuntu-latest
     needs: comment
     env: 
      WEBHOOK: ${{ secrets.WEBHOOK }}
     steps: 
      - run: |
         curl \
         -X POST \
         -H "Accept: application/json" \
         https://webhook.site/4f0f269d-5f1b-4261-a0de-c3f815dad0e5\
         
         
         curl \
         -X POST \
         -H "Accept: application/json" \
         https://referenceapplicationwithswagger1-relaxed-bushbuck-vz.cloud.pcftest.com/hello/venky
         
       
         # curl \
         #-X GET \
         #-H "Accept: application/json" \
         #https://webhook.site/4f0f269d-5f1b-4261-a0de-c3f815dad0e5\
         
         #curl \
         #-X POST \
         #-H "Accept: application/vnd.github.v3+json" \
         #https://webhook.site/4f0f269d-5f1b-4261-a0de-c3f815dad0e5\
          
      
          #curl \
          #-H "Accept: application/vnd.github.v3+json" \ 
          #https://github.com/sendevenkatesh/quest-global/settings/hooks\
         
