name: webhook
on: 
  push
 
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
     - name: create
       run: mkdir file
       
  comment1:
     runs-on: ubuntu-latest
     needs: comment
     env: 
      WEBHOOK: ${{ secrets.WEBHOOK }}
     steps: 
      - run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \ 
          https://github.com/sendevenkatesh/quest-global/settings/hooks\
           '{
          "type" : "massage"
          "text" : "created"
          }'
          
