name: java CI with Gradle

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up jdk 1.8
      uses: actions/setup-java@v1
      with:
         java-version: 1.8
    - name: grant execute permission for gradlew
      run: chmod +x gradlew
    - name: build with gradle
      run: ./gradlew build

    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: repo/alpine  ##docker-hub-repo/image-name
        tags: v1, latest
        registry: Docker.io
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

//## Dockerfile.ci

FROM alpine:3 AS download ## base image
RUN mkdir -p /usr/bin/cf
COPY . /bin/cf
WORKDIR /bin/cf
RUN apk update \
 && apk add curl \
 && curl -sL 'https://packages.cloudfoundry.org/stable?release=linux64-binary&version=6.53.0&source=github-rel' | tar -xzv \
 && chmod 0755 cf

FROM alpine:3
COPY --from=download /cf /usr/bin/cf
COPY entrypoint.sh /entrypoint.sh
EXPOSE 8080
ENTRYPOINT ["/entrypoint.sh"]//

