on:
  push:
    branches:
    - 'main'
  
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
 
    - name: Test
      run: ./gradlew
          

    - run: |
        mkdir -p ${{ github.workspace }}/artifact
        echo hello > ${{ github.workspace }}/artifact/world.txt
      
    - name: my-artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/artifact/word.txt
    
  

    
         
