name: java CI with gradle
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          mkdir venky
          touch file1
      - shell: bash
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/quest-global/hello-world/hooks


