on:
  push:
    branches:
    - 'main'
env:
  version-source: file
  version-file: build.gradle
  
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Generate versions
      uses: sendevenkatesh/quest-global@main
      with:
        version-source: file
        version-file: ${{ env.version-file }}
        version-file-extraction-pattern: '(?<=version=).+'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Release with Gradle
      id: release
      run: |
        ./gradlew release -Prelease.useAutomaticVersion=true \
        -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} \
        -Prelease.newVersion=${{ env.NEXT_VERSION }}
         
