name: java CI with gradle
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          mkdir venky
          touch file1
      - shell: bash
        run: |
          expr 1 + 1 > output.log


