name: Create an issue on push
on: [push]
permissions:
  contents: read
  issues: write 
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
  comment1:
     runs-on: ubuntu-latest
     needs: comment
     #env: 
      #WEBHOOK: ${{ secrets.WEBHOOK }}
     steps: 
      - run: |
          curl -d '{"type":"messege", "text":"New issue"}' \
          -H "Content-Type: application/json" \
          -X POST https://webhook.site/4f0f269d-5f1b-4261-a0de-c3f815dad0e5
          
         
         #curl \
         #-X GET \
         #-H "Accept: application/json" \
         #https://referenceapplicationwithswagger1-relaxed-bushbuck-vz.cloud.pcftest.com/hello/vamshi
         
       
         
